### ISSUE TITLE
Firmware v1.15.13_20230203 Touchscreen Inconsistencies

### ISSUE THREAD

**Issue by darienm** [Snapmaker/Snapmaker2-Firmware-Issues#6]
Snapmaker 2.0 A350 with Dual Extruder toolhead.
1. While printing, the "Right Z Offset" screen displays "Left Z Offset" as the title at the top.
2. The screens for Z Offset and Flow Rate place the position identifier "Left" or "Right" as the first word in the screen title, but the Nozzle screen displays "Nozzle L" and "Nozzle R" which has an abbreviated position identifier at the end of the tabs at the top. This is inconsistent.
![cap_2935](https://user-images.githubusercontent.com/2875381/216743896-84dd2268-c5af-4107-8fd5-2f82e3d240df.png)
![cap_2936](https://user-images.githubusercontent.com/2875381/216743900-05d4bdd4-0fab-44ec-b891-633f097cc9b2.png)

**Comment by WZiting** [comment]
Fixed in v1.15.17
