### ISSUE TITLE
Firmware v1.15.13_20230203 

### ISSUE THREAD

**Issue by darienm** [Snapmaker/Snapmaker2-Firmware-Issues#7]
After a full initial calibration of the bed and both nozzles on the Dual Extruder (Snapmaker 2.0 A350) when printing the first calibration model the left nozzle required a +0.6mm z-offset correction to get a proper first layer. That seems like a significant error.

**Comment by WZiting** [comment]
Try sensor calibration and then recalibrate Zoffset.
